### ISSUE TITLE
Actions don't work

### ISSUE THREAD

**Issue by mshtang** [theme-keep/hexo-deploy-github-pages-action#1]
Hi,
Thank you for sharing the action and creating the beautiful theme!

I followed [this](https://keep.xpoet.cn/2021/03/%E4%BD%BF%E7%94%A8-GitHub-Action-%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2-Hexo-%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2/) tutorial step by step trying to setup the GitHub actions to automatically build and deploy but didn't succeed.

What I noticed is that, after running the actions in my private repo (which contains the blog source), four folders are missing in the public repo (which holds the static pages), namely `css`, `images`, `js` and `webfonts` when compared to manual deployment by running `hexo d -g` in my local repo. Please see the sceenshots below.

_using GitHub actions_
![auto](https://user-images.githubusercontent.com/32868278/112749575-7a689100-8fc3-11eb-8782-4def340c8b3e.jpg)

_manual deployment_
![manuel](https://user-images.githubusercontent.com/32868278/112749587-85232600-8fc3-11eb-807c-37e7af898d9b.jpg)

Is there something missing in the `hexo-workflow.yml` or something else needs to be setup?

Thanks again for any help with resolving this issue!

**Comment by daniel18qzx** [comment]
我这边发现action跑出来的index.html是空的

**Comment by XPoet** [comment]
@mshtang 

Take a look at the contents of your `hexo-workflow.yml ` file

**Comment by XPoet** [comment]
This action can be used normally in my Hexo project

```yaml
name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
          PUBLISH_REPOSITORY: theme-keep/site
          BRANCH: gh-pages
          PUBLISH_DIR: ./public
```

**Comment by mshtang** [comment]
Hi, thanks for the answer.

Here's what's in my `hexo-deploy.yml` file:
```
name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
          PUBLISH_REPOSITORY: mshtang/mshtang.github.io
          BRANCH: master
          PUBLISH_DIR: ./public
```
personal token has been setup. I changed the `publish_repo` accordingly to my repo. Do I need to add/customize something else? Thank you!

**Comment by naichaduck** [comment]
> Hi, thanks for the answer.
> 
> Here's what's in my `hexo-deploy.yml` file:
> 
> ```
> name: deploying Hexo project to GitHub pages
> on:
>   push:
>     branches:
>       - master
> 
> jobs:
>   build-and-deploy:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@master
> 
>       - name: Build and Deploy
>         uses: theme-keep/hexo-deploy-github-pages-action@master
>         env:
>           PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
>           PUBLISH_REPOSITORY: mshtang/mshtang.github.io
>           BRANCH: master
>           PUBLISH_DIR: ./public
> ```
> 
> personal token has been setup. I changed the `publish_repo` accordingly to my repo. Do I need to add/customize something else? Thank you!

I have the same problem, is it fixed by now?

**Comment by ruoan777** [comment]
> 我这边发现action跑出来的index.html是空的

我这边跑出来的index.html也有问题，显示的似乎是Keep主题原始的index.html，我的配置没有生效。
而本地 hexo generate 命令生成的index.html是没有问题的

**Comment by ruoan777** [comment]
这个action目前还有维护嘛

**Comment by stuchilde** [comment]
我也遇到了用这个github action部署后html文件是空的。

**Comment by Itoktsnhc** [comment]
@stuchilde  @ruoan777  
index生成不成功可能是因为hexo的主题都使用了 sub module的形式。
尝试修改 steps中的checkout步骤:
``` yml
steps:
- name: Checkout repository and submodules
  uses: actions/checkout@v2
  with:
    submodules: recursive
```
