### ISSUE TITLE
找不到配置的仓库分支

### ISSUE THREAD

**Issue by sonderss** [theme-keep/hexo-deploy-github-pages-action#9]
我的yml: 
```
name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
          PUBLISH_REPOSITORY:  xx/xx.github.io  # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: gh-pages    # 分支，填 gh-pages 就行
          PUBLISH_DIR: ./public # 部署 public 目录下的文件
```
执行步骤： 
1.   git add  .
 2.  git commit -m  '提交代码'
 3. git push

执行结果： 
```
>>> Config git ...
Initialized empty Git repository in /github/workspace/public/.git/
fatal: not in a git directory
```

期望结果： 
```
>>> Config git ...
Initialized empty Git repository in /github/workspace/public/.git/
Switched to a new branch 'gh-pages'
```
